```{r, include=FALSE}
library(latex)
library(enotation) # R() RStudio()
library(emargintag) # :::TODO
library(emedia)
library(webshot)
library(knitr)
#library(linguisticsdown)
```


```{r setup, include=FALSE}
#knit
knitr::opts_chunk$set(
    echo = TRUE, 
    fig.retina = 2, 
    fig.align = "center",
    out.width="80%",
    message=FALSE,
    warning=FALSE,
    error=FALSE,
    results = 'hold',
    #
    # https://bookdown.org/yihui/rmarkdown-cookbook/opts-tidy.html
    #tidy=TRUE, 
    #tidy.opts=list(width.cutoff=60)
    #
    # Trick to be able to customize default output (see pre.egitbook-output in style.css)
    # Idea de:
    # https://stackoverflow.com/questions/65495605/in-r-bookdown-how-do-i-set-the-default-code-output-background-color
    class.output = 'egitbook-output'    
)

# comment (salida)
if(knitr::is_html_output()){
    knitr::opts_chunk$set(comment = '')    
}
if(knitr::is_latex_output()){
    knitr::opts_chunk$set(comment = '##')    
}

# -shell-escape
# https://stackoverflow.com/questions/55459948/latex-shell-escape-options-in-yaml-header-dont-use?noredirect=1#comment97651281_55459948
options(tinytex.engine_args = '-halt-on-error -interaction=nonstopmode -shell-escape') 

## numbers >= 10^5 will be denoted in scientific notation,
## and rounded to 3 digits
options(scipen = 0, digits = 7)
## inline
#inline_hook <- function(x) {
#  if (is.numeric(x)) {
#    format(x, digits = 2)
#  } else x
#}
#knitr::knit_hooks$set(inline = inline_hook)

# usar versión más reciente de pandoc
rmarkdown::find_pandoc()
```

```{r wrap-hook, include=FALSE}
# https://github.com/yihui/knitr-examples/blob/master/077-wrap-output.Rmd
hook_output = knit_hooks$get('output')
knit_hooks$set(output = function(x, options) {
  # this hook is used only when the linewidth option is not NULL
  if (!is.null(n <- options$linewidth)) {
    x = knitr:::split_lines(x)
    # any lines wider than n should be wrapped
    if (any(nchar(x) > n)) x = strwrap(x, width = n)
    x = paste(x, collapse = '\n')
  }
  hook_output(x, options)
})
# default
knitr::opts_chunk$set(
    linewidth = 60
)
```


```{r lastvalue, include=FALSE}
# Para poder usar .Last.value  como en consola (más o menos)
# https://stackoverflow.com/questions/31475226/using-last-value-in-rmarkdown-knitr
knitr::opts_chunk$set(render = function(x, ...){
    unlockBinding(".Last.value", .BaseNamespaceEnv)
    assign(".Last.value", x, .BaseNamespaceEnv)
    lockBinding(".Last.value", .BaseNamespaceEnv)
    knitr::knit_print(x, ...)
})
```



```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(
    c(
        .packages(), 
        'bookdown', 
        'knitr', 
        'rmarkdown'
    ), 
    'packages.bib'
)
```


```{r, include=FALSE}
    degree <- rmarkdown::metadata$degree
```
